package com.nalashaa.fhir.db.model;

// Generated Dec 16, 2016 10:45:37 PM by Hibernate Tools 4.0.0.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Immunization generated by hbm2java
 */
@Entity
@Table(name = "immunization", catalog = "qrda")
public class Immunization implements java.io.Serializable {

	private Integer immzId;
	private Integer cid;
	private String immunization;
	private String vaccineLot;
	private String manufacturer;
	private Date expirationDate;
	private String informationSource;
	private String registryStatus;
	private String administeredAmount;
	private String administeredUnit;
	private Date dateTimeAdministered;
	private String administeredAt;
	private String administeringProviderLastName;
	private String administeringProviderMiddleName;
	private String administeringProviderFirstName;
	private String administrationRoute;
	private String vaccineFundingObsMethod;
	private Date visPresentationDate;
	private String fundingProgramEligCategory;
	private String noVaccineAdministered;
	private String evidenceOfImmunity;
	private String substanceRefusalReason;
	private String orderByLastName;
	private String orderByMiddleName;
	private String orderByFirstName;
	private String administeredLocation;
	private String fillerOrderNumber;
	private String administrationNote;
	private Date createdDate;
	private String createdBy;
	private Date updatedDate;
	private String updatedBy;
	private String administeringProviderId;
	private String orderByProviderId;
	private Date lastExportedDate;

	public Immunization() {
	}

	public Immunization(String fillerOrderNumber) {
		this.fillerOrderNumber = fillerOrderNumber;
	}

	public Immunization(Integer cid, String immunization, String vaccineLot, String manufacturer, Date expirationDate,
			String informationSource, String registryStatus, String administeredAmount, String administeredUnit,
			Date dateTimeAdministered, String administeredAt, String administeringProviderLastName,
			String administeringProviderMiddleName, String administeringProviderFirstName, String administrationRoute,
			String vaccineFundingObsMethod, Date visPresentationDate, String fundingProgramEligCategory,
			String noVaccineAdministered, String evidenceOfImmunity, String substanceRefusalReason,
			String orderByLastName, String orderByMiddleName, String orderByFirstName, String administeredLocation,
			String fillerOrderNumber, String administrationNote, Date createdDate, String createdBy, Date updatedDate,
			String updatedBy, String administeringProviderId, String orderByProviderId, Date lastExportedDate) {
		this.cid = cid;
		this.immunization = immunization;
		this.vaccineLot = vaccineLot;
		this.manufacturer = manufacturer;
		this.expirationDate = expirationDate;
		this.informationSource = informationSource;
		this.registryStatus = registryStatus;
		this.administeredAmount = administeredAmount;
		this.administeredUnit = administeredUnit;
		this.dateTimeAdministered = dateTimeAdministered;
		this.administeredAt = administeredAt;
		this.administeringProviderLastName = administeringProviderLastName;
		this.administeringProviderMiddleName = administeringProviderMiddleName;
		this.administeringProviderFirstName = administeringProviderFirstName;
		this.administrationRoute = administrationRoute;
		this.vaccineFundingObsMethod = vaccineFundingObsMethod;
		this.visPresentationDate = visPresentationDate;
		this.fundingProgramEligCategory = fundingProgramEligCategory;
		this.noVaccineAdministered = noVaccineAdministered;
		this.evidenceOfImmunity = evidenceOfImmunity;
		this.substanceRefusalReason = substanceRefusalReason;
		this.orderByLastName = orderByLastName;
		this.orderByMiddleName = orderByMiddleName;
		this.orderByFirstName = orderByFirstName;
		this.administeredLocation = administeredLocation;
		this.fillerOrderNumber = fillerOrderNumber;
		this.administrationNote = administrationNote;
		this.createdDate = createdDate;
		this.createdBy = createdBy;
		this.updatedDate = updatedDate;
		this.updatedBy = updatedBy;
		this.administeringProviderId = administeringProviderId;
		this.orderByProviderId = orderByProviderId;
		this.lastExportedDate = lastExportedDate;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "immzId", unique = true, nullable = false)
	public Integer getImmzId() {
		return this.immzId;
	}

	public void setImmzId(Integer immzId) {
		this.immzId = immzId;
	}

	@Column(name = "cId")
	public Integer getCid() {
		return this.cid;
	}

	public void setCid(Integer cid) {
		this.cid = cid;
	}

	@Column(name = "immunization", length = 200)
	public String getImmunization() {
		return this.immunization;
	}

	public void setImmunization(String immunization) {
		this.immunization = immunization;
	}

	@Column(name = "vaccineLot", length = 200)
	public String getVaccineLot() {
		return this.vaccineLot;
	}

	public void setVaccineLot(String vaccineLot) {
		this.vaccineLot = vaccineLot;
	}

	@Column(name = "manufacturer", length = 200)
	public String getManufacturer() {
		return this.manufacturer;
	}

	public void setManufacturer(String manufacturer) {
		this.manufacturer = manufacturer;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "expirationDate", length = 0)
	public Date getExpirationDate() {
		return this.expirationDate;
	}

	public void setExpirationDate(Date expirationDate) {
		this.expirationDate = expirationDate;
	}

	@Column(name = "informationSource", length = 200)
	public String getInformationSource() {
		return this.informationSource;
	}

	public void setInformationSource(String informationSource) {
		this.informationSource = informationSource;
	}

	@Column(name = "registryStatus", length = 200)
	public String getRegistryStatus() {
		return this.registryStatus;
	}

	public void setRegistryStatus(String registryStatus) {
		this.registryStatus = registryStatus;
	}

	@Column(name = "administeredAmount", length = 200)
	public String getAdministeredAmount() {
		return this.administeredAmount;
	}

	public void setAdministeredAmount(String administeredAmount) {
		this.administeredAmount = administeredAmount;
	}

	@Column(name = "administeredUnit", length = 200)
	public String getAdministeredUnit() {
		return this.administeredUnit;
	}

	public void setAdministeredUnit(String administeredUnit) {
		this.administeredUnit = administeredUnit;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "dateTimeAdministered", length = 0)
	public Date getDateTimeAdministered() {
		return this.dateTimeAdministered;
	}

	public void setDateTimeAdministered(Date dateTimeAdministered) {
		this.dateTimeAdministered = dateTimeAdministered;
	}

	@Column(name = "administeredAt", length = 200)
	public String getAdministeredAt() {
		return this.administeredAt;
	}

	public void setAdministeredAt(String administeredAt) {
		this.administeredAt = administeredAt;
	}

	@Column(name = "administeringProviderLastName", length = 200)
	public String getAdministeringProviderLastName() {
		return this.administeringProviderLastName;
	}

	public void setAdministeringProviderLastName(String administeringProviderLastName) {
		this.administeringProviderLastName = administeringProviderLastName;
	}

	@Column(name = "administeringProviderMiddleName", length = 200)
	public String getAdministeringProviderMiddleName() {
		return this.administeringProviderMiddleName;
	}

	public void setAdministeringProviderMiddleName(String administeringProviderMiddleName) {
		this.administeringProviderMiddleName = administeringProviderMiddleName;
	}

	@Column(name = "administeringProviderFirstName", length = 200)
	public String getAdministeringProviderFirstName() {
		return this.administeringProviderFirstName;
	}

	public void setAdministeringProviderFirstName(String administeringProviderFirstName) {
		this.administeringProviderFirstName = administeringProviderFirstName;
	}

	@Column(name = "administrationRoute", length = 200)
	public String getAdministrationRoute() {
		return this.administrationRoute;
	}

	public void setAdministrationRoute(String administrationRoute) {
		this.administrationRoute = administrationRoute;
	}

	@Column(name = "vaccineFundingObsMethod", length = 200)
	public String getVaccineFundingObsMethod() {
		return this.vaccineFundingObsMethod;
	}

	public void setVaccineFundingObsMethod(String vaccineFundingObsMethod) {
		this.vaccineFundingObsMethod = vaccineFundingObsMethod;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "visPresentationDate", length = 0)
	public Date getVisPresentationDate() {
		return this.visPresentationDate;
	}

	public void setVisPresentationDate(Date visPresentationDate) {
		this.visPresentationDate = visPresentationDate;
	}

	@Column(name = "fundingProgramEligCategory", length = 200)
	public String getFundingProgramEligCategory() {
		return this.fundingProgramEligCategory;
	}

	public void setFundingProgramEligCategory(String fundingProgramEligCategory) {
		this.fundingProgramEligCategory = fundingProgramEligCategory;
	}

	@Column(name = "noVaccineAdministered", length = 200)
	public String getNoVaccineAdministered() {
		return this.noVaccineAdministered;
	}

	public void setNoVaccineAdministered(String noVaccineAdministered) {
		this.noVaccineAdministered = noVaccineAdministered;
	}

	@Column(name = "evidenceOfImmunity", length = 200)
	public String getEvidenceOfImmunity() {
		return this.evidenceOfImmunity;
	}

	public void setEvidenceOfImmunity(String evidenceOfImmunity) {
		this.evidenceOfImmunity = evidenceOfImmunity;
	}

	@Column(name = "substanceRefusalReason", length = 200)
	public String getSubstanceRefusalReason() {
		return this.substanceRefusalReason;
	}

	public void setSubstanceRefusalReason(String substanceRefusalReason) {
		this.substanceRefusalReason = substanceRefusalReason;
	}

	@Column(name = "orderByLastName", length = 200)
	public String getOrderByLastName() {
		return this.orderByLastName;
	}

	public void setOrderByLastName(String orderByLastName) {
		this.orderByLastName = orderByLastName;
	}

	@Column(name = "orderByMiddleName", length = 200)
	public String getOrderByMiddleName() {
		return this.orderByMiddleName;
	}

	public void setOrderByMiddleName(String orderByMiddleName) {
		this.orderByMiddleName = orderByMiddleName;
	}

	@Column(name = "orderByFirstName", length = 200)
	public String getOrderByFirstName() {
		return this.orderByFirstName;
	}

	public void setOrderByFirstName(String orderByFirstName) {
		this.orderByFirstName = orderByFirstName;
	}

	@Column(name = "administeredLocation", length = 200)
	public String getAdministeredLocation() {
		return this.administeredLocation;
	}

	public void setAdministeredLocation(String administeredLocation) {
		this.administeredLocation = administeredLocation;
	}

	@Column(name = "fillerOrderNumber", nullable = false, length = 200)
	public String getFillerOrderNumber() {
		return this.fillerOrderNumber;
	}

	public void setFillerOrderNumber(String fillerOrderNumber) {
		this.fillerOrderNumber = fillerOrderNumber;
	}

	@Column(name = "administrationNote", length = 200)
	public String getAdministrationNote() {
		return this.administrationNote;
	}

	public void setAdministrationNote(String administrationNote) {
		this.administrationNote = administrationNote;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "createdDate", length = 0)
	public Date getCreatedDate() {
		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	@Column(name = "createdBy", length = 200)
	public String getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(String createdBy) {
		this.createdBy = createdBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "updatedDate", length = 0)
	public Date getUpdatedDate() {
		return this.updatedDate;
	}

	public void setUpdatedDate(Date updatedDate) {
		this.updatedDate = updatedDate;
	}

	@Column(name = "updatedBy", length = 200)
	public String getUpdatedBy() {
		return this.updatedBy;
	}

	public void setUpdatedBy(String updatedBy) {
		this.updatedBy = updatedBy;
	}

	@Column(name = "administeringProviderId", length = 100)
	public String getAdministeringProviderId() {
		return this.administeringProviderId;
	}

	public void setAdministeringProviderId(String administeringProviderId) {
		this.administeringProviderId = administeringProviderId;
	}

	@Column(name = "orderByProviderId", length = 100)
	public String getOrderByProviderId() {
		return this.orderByProviderId;
	}

	public void setOrderByProviderId(String orderByProviderId) {
		this.orderByProviderId = orderByProviderId;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "lastExportedDate", length = 0)
	public Date getLastExportedDate() {
		return this.lastExportedDate;
	}

	public void setLastExportedDate(Date lastExportedDate) {
		this.lastExportedDate = lastExportedDate;
	}

}
