package com.nalashaa.fhir.server.acl.db.model;
// default package
// Generated Dec 16, 2016 10:45:37 PM by Hibernate Tools 4.0.0.Final

import static javax.persistence.GenerationType.IDENTITY;

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.hibernate.annotations.DynamicInsert;
import org.hibernate.annotations.DynamicUpdate;
import org.hibernate.annotations.SelectBeforeUpdate;

/**
 * Contacts generated by hbm2java
 */
@Entity
@DynamicInsert
@SelectBeforeUpdate(true)
@DynamicUpdate(true)
@Table(name = "contacts", catalog = "qrda")
public class PatientEn implements java.io.Serializable {

	private Integer cid;
	private String type;
	private String owner;
	private String company;
	private String companyContact;
	private String prefix;
	private String fname;
	private String mname;
	private String lname;
	private String credentials;
	private String nickname;
	private String spouse;
	private String birthday;
	private String sex;
	private String title;
	private String employer;
	private String address11;
	private String address12;
	private String city1;
	private String state1;
	private String zip1;
	private String country1;
	private String address21;
	private String address22;
	private String city2;
	private String state2;
	private String zip2;
	private String country2;
	private int mailto;
	private String hphone;
	private String wphone1;
	private String wphone2;
	private String mphone;
	private int phoneto;
	private String fax1;
	private String fax2;
	private String email1;
	private String email2;
	private int emailto;
	private String url;
	private byte acuity;
	private String pricontact;
	private String category;
	private String comments;
	private String abstract_;
	private String audit;
	private boolean active;
	private String dirid;
	private String import_;
	private String dob;
	private String doa;
	private String edoa;
	private String dod;
	private String edod;
	private String initialcontact;
	private String ethnic;
	private String religion;
	private String liveswith;
	private String ssnum;
	private String provider;
	private String provider2;
	private String provider3;
	private String provider4;
	private String altid;
	private String globalid;
	private String pgroup;
	private String school;
	private String grade;
	private String lupdate;
	private String location;
	private String referrer;
	private String salutation;
	private boolean qualified;
	private String inactiveReason;
	private String pin;
	private String bnid;
	private byte readonly;
	private byte undeleteable;
	private int feeSchedule;
	private int transgender;
	private int facilityId;
	private String cashOnly;
	private int ethnicityId;
	private int smokingStatusId;
	private Date smokingStatusDate;
	private String motherMaidenName;
	private String maritalStatusCode;
	private String languageCode;
	private String communicationPreference;
	private String nextOfKin;
	private int mpi;

	public PatientEn() {
	}

//	public PatientEn(String type, String owner, String company, String companyContact, String prefix, String fname,
//			String mname, String lname, String credentials, String nickname, String spouse, String birthday, String sex,
//			String title, String employer, String address11, String address12, String city1, String state1, String zip1,
//			String country1, String address21, String address22, String city2, String state2, String zip2,
//			String country2, int mailto, String hphone, String wphone1, String wphone2, String mphone, int phoneto,
//			String fax1, String fax2, String email1, String email2, int emailto, String url, byte acuity,
//			String pricontact, String category, String comments, String abstract_, String audit, boolean active,
//			String dirid, String import_, String dob, String doa, String edoa, String dod, String edod,
//			String initialcontact, String ethnic, String religion, String liveswith, String ssnum, String provider,
//			String provider2, String provider3, String provider4, String altid, String globalid, String pgroup,
//			String school, String grade, String lupdate, String location, String referrer, String salutation,
//			boolean qualified, String inactiveReason, String pin, String bnid, byte readonly, byte undeleteable,
//			int feeSchedule, int transgender, int facilityId, String cashOnly, int ethnicityId, int smokingStatusId,
//			Date smokingStatusDate, String motherMaidenName, String maritalStatusCode, String languageCode,
//			String communicationPreference, int mpi) {
//		this.type = type;
//		this.owner = owner;
//		this.company = company;
//		this.companyContact = companyContact;
//		this.prefix = prefix;
//		this.fname = fname;
//		this.mname = mname;
//		this.lname = lname;
//		this.credentials = credentials;
//		this.nickname = nickname;
//		this.spouse = spouse;
//		this.birthday = birthday;
//		this.sex = sex;
//		this.title = title;
//		this.employer = employer;
//		this.address11 = address11;
//		this.address12 = address12;
//		this.city1 = city1;
//		this.state1 = state1;
//		this.zip1 = zip1;
//		this.country1 = country1;
//		this.address21 = address21;
//		this.address22 = address22;
//		this.city2 = city2;
//		this.state2 = state2;
//		this.zip2 = zip2;
//		this.country2 = country2;
//		this.mailto = mailto;
//		this.hphone = hphone;
//		this.wphone1 = wphone1;
//		this.wphone2 = wphone2;
//		this.mphone = mphone;
//		this.phoneto = phoneto;
//		this.fax1 = fax1;
//		this.fax2 = fax2;
//		this.email1 = email1;
//		this.email2 = email2;
//		this.emailto = emailto;
//		this.url = url;
//		this.acuity = acuity;
//		this.pricontact = pricontact;
//		this.category = category;
//		this.comments = comments;
//		this.abstract_ = abstract_;
//		this.audit = audit;
//		this.active = active;
//		this.dirid = dirid;
//		this.import_ = import_;
//		this.dob = dob;
//		this.doa = doa;
//		this.edoa = edoa;
//		this.dod = dod;
//		this.edod = edod;
//		this.initialcontact = initialcontact;
//		this.ethnic = ethnic;
//		this.religion = religion;
//		this.liveswith = liveswith;
//		this.ssnum = ssnum;
//		this.provider = provider;
//		this.provider2 = provider2;
//		this.provider3 = provider3;
//		this.provider4 = provider4;
//		this.altid = altid;
//		this.globalid = globalid;
//		this.pgroup = pgroup;
//		this.school = school;
//		this.grade = grade;
//		this.lupdate = lupdate;
//		this.location = location;
//		this.referrer = referrer;
//		this.salutation = salutation;
//		this.qualified = qualified;
//		this.inactiveReason = inactiveReason;
//		this.pin = pin;
//		this.bnid = bnid;
//		this.readonly = readonly;
//		this.undeleteable = undeleteable;
//		this.feeSchedule = feeSchedule;
//		this.transgender = transgender;
//		this.facilityId = facilityId;
//		this.cashOnly = cashOnly;
//		this.ethnicityId = ethnicityId;
//		this.smokingStatusId = smokingStatusId;
//		this.smokingStatusDate = smokingStatusDate;
//		this.motherMaidenName = motherMaidenName;
//		this.maritalStatusCode = maritalStatusCode;
//		this.languageCode = languageCode;
//		this.communicationPreference = communicationPreference;
//		this.mpi = mpi;
//	}
//
//	public PatientEn(String type, String owner, String company, String companyContact, String prefix, String fname,
//			String mname, String lname, String credentials, String nickname, String spouse, String birthday, String sex,
//			String title, String employer, String address11, String address12, String city1, String state1, String zip1,
//			String country1, String address21, String address22, String city2, String state2, String zip2,
//			String country2, int mailto, String hphone, String wphone1, String wphone2, String mphone, int phoneto,
//			String fax1, String fax2, String email1, String email2, int emailto, String url, byte acuity,
//			String pricontact, String category, String comments, String abstract_, String audit, boolean active,
//			String dirid, String import_, String dob, String doa, String edoa, String dod, String edod,
//			String initialcontact, String ethnic, String religion, String liveswith, String ssnum, String provider,
//			String provider2, String provider3, String provider4, String altid, String globalid, String pgroup,
//			String school, String grade, String lupdate, String location, String referrer, String salutation,
//			boolean qualified, String inactiveReason, String pin, String bnid, byte readonly, byte undeleteable,
//			int feeSchedule, int transgender, int facilityId, String cashOnly, int ethnicityId, int smokingStatusId,
//			Date smokingStatusDate, String motherMaidenName, String maritalStatusCode, String languageCode,
//			String communicationPreference, String nextOfKin, int mpi) {
//		this.type = type;
//		this.owner = owner;
//		this.company = company;
//		this.companyContact = companyContact;
//		this.prefix = prefix;
//		this.fname = fname;
//		this.mname = mname;
//		this.lname = lname;
//		this.credentials = credentials;
//		this.nickname = nickname;
//		this.spouse = spouse;
//		this.birthday = birthday;
//		this.sex = sex;
//		this.title = title;
//		this.employer = employer;
//		this.address11 = address11;
//		this.address12 = address12;
//		this.city1 = city1;
//		this.state1 = state1;
//		this.zip1 = zip1;
//		this.country1 = country1;
//		this.address21 = address21;
//		this.address22 = address22;
//		this.city2 = city2;
//		this.state2 = state2;
//		this.zip2 = zip2;
//		this.country2 = country2;
//		this.mailto = mailto;
//		this.hphone = hphone;
//		this.wphone1 = wphone1;
//		this.wphone2 = wphone2;
//		this.mphone = mphone;
//		this.phoneto = phoneto;
//		this.fax1 = fax1;
//		this.fax2 = fax2;
//		this.email1 = email1;
//		this.email2 = email2;
//		this.emailto = emailto;
//		this.url = url;
//		this.acuity = acuity;
//		this.pricontact = pricontact;
//		this.category = category;
//		this.comments = comments;
//		this.abstract_ = abstract_;
//		this.audit = audit;
//		this.active = active;
//		this.dirid = dirid;
//		this.import_ = import_;
//		this.dob = dob;
//		this.doa = doa;
//		this.edoa = edoa;
//		this.dod = dod;
//		this.edod = edod;
//		this.initialcontact = initialcontact;
//		this.ethnic = ethnic;
//		this.religion = religion;
//		this.liveswith = liveswith;
//		this.ssnum = ssnum;
//		this.provider = provider;
//		this.provider2 = provider2;
//		this.provider3 = provider3;
//		this.provider4 = provider4;
//		this.altid = altid;
//		this.globalid = globalid;
//		this.pgroup = pgroup;
//		this.school = school;
//		this.grade = grade;
//		this.lupdate = lupdate;
//		this.location = location;
//		this.referrer = referrer;
//		this.salutation = salutation;
//		this.qualified = qualified;
//		this.inactiveReason = inactiveReason;
//		this.pin = pin;
//		this.bnid = bnid;
//		this.readonly = readonly;
//		this.undeleteable = undeleteable;
//		this.feeSchedule = feeSchedule;
//		this.transgender = transgender;
//		this.facilityId = facilityId;
//		this.cashOnly = cashOnly;
//		this.ethnicityId = ethnicityId;
//		this.smokingStatusId = smokingStatusId;
//		this.smokingStatusDate = smokingStatusDate;
//		this.motherMaidenName = motherMaidenName;
//		this.maritalStatusCode = maritalStatusCode;
//		this.languageCode = languageCode;
//		this.communicationPreference = communicationPreference;
//		this.nextOfKin = nextOfKin;
//		this.mpi = mpi;
//	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "CID", unique = true, nullable = false)
	public Integer getCid() {
		return this.cid;
	}

	public void setCid(Integer cid) {
		this.cid = cid;
	}

	@Column(name = "TYPE", nullable = false, length = 24)
	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

	@Column(name = "OWNER", nullable = false, length = 14)
	public String getOwner() {
		return this.owner;
	}

	public void setOwner(String owner) {
		this.owner = owner;
	}

	@Column(name = "COMPANY", nullable = false, length = 72)
	public String getCompany() {
		return this.company;
	}

	public void setCompany(String company) {
		this.company = company;
	}

	@Column(name = "COMPANY_CONTACT", nullable = false, length = 72)
	public String getCompanyContact() {
		return this.companyContact;
	}

	public void setCompanyContact(String companyContact) {
		this.companyContact = companyContact;
	}

	@Column(name = "PREFIX", nullable = false, length = 24)
	public String getPrefix() {
		return this.prefix;
	}

	public void setPrefix(String prefix) {
		this.prefix = prefix;
	}

	@Column(name = "FNAME", nullable = false, length = 36)
	public String getFname() {
		return this.fname;
	}

	public void setFname(String fname) {
		this.fname = fname;
	}

	@Column(name = "MNAME", nullable = false, length = 36)
	public String getMname() {
		return this.mname;
	}

	public void setMname(String mname) {
		this.mname = mname;
	}

	@Column(name = "LNAME", nullable = false, length = 36)
	public String getLname() {
		return this.lname;
	}

	public void setLname(String lname) {
		this.lname = lname;
	}

	@Column(name = "CREDENTIALS", nullable = false, length = 72)
	public String getCredentials() {
		return this.credentials;
	}

	public void setCredentials(String credentials) {
		this.credentials = credentials;
	}

	@Column(name = "NICKNAME", nullable = false, length = 48)
	public String getNickname() {
		return this.nickname;
	}

	public void setNickname(String nickname) {
		this.nickname = nickname;
	}

	@Column(name = "SPOUSE", nullable = false, length = 36)
	public String getSpouse() {
		return this.spouse;
	}

	public void setSpouse(String spouse) {
		this.spouse = spouse;
	}

	@Column(name = "BIRTHDAY", nullable = false, length = 24)
	public String getBirthday() {
		return this.birthday;
	}

	public void setBirthday(String birthday) {
		this.birthday = birthday;
	}

	@Column(name = "SEX", nullable = false, length = 14)
	public String getSex() {
		return this.sex;
	}

	public void setSex(String sex) {
		this.sex = sex;
	}

	@Column(name = "TITLE", nullable = false, length = 36)
	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	@Column(name = "EMPLOYER", nullable = false, length = 72)
	public String getEmployer() {
		return this.employer;
	}

	public void setEmployer(String employer) {
		this.employer = employer;
	}

	@Column(name = "ADDRESS1_1", nullable = false, length = 72)
	public String getAddress11() {
		return this.address11;
	}

	public void setAddress11(String address11) {
		this.address11 = address11;
	}

	@Column(name = "ADDRESS1_2", nullable = false, length = 72)
	public String getAddress12() {
		return this.address12;
	}

	public void setAddress12(String address12) {
		this.address12 = address12;
	}

	@Column(name = "CITY1", nullable = false, length = 24)
	public String getCity1() {
		return this.city1;
	}

	public void setCity1(String city1) {
		this.city1 = city1;
	}

	@Column(name = "STATE1", nullable = false, length = 24)
	public String getState1() {
		return this.state1;
	}

	public void setState1(String state1) {
		this.state1 = state1;
	}

	@Column(name = "ZIP1", nullable = false, length = 24)
	public String getZip1() {
		return this.zip1;
	}

	public void setZip1(String zip1) {
		this.zip1 = zip1;
	}

	@Column(name = "COUNTRY1", nullable = false, length = 24)
	public String getCountry1() {
		return this.country1;
	}

	public void setCountry1(String country1) {
		this.country1 = country1;
	}

	@Column(name = "ADDRESS2_1", nullable = false, length = 72)
	public String getAddress21() {
		return this.address21;
	}

	public void setAddress21(String address21) {
		this.address21 = address21;
	}

	@Column(name = "ADDRESS2_2", nullable = false, length = 72)
	public String getAddress22() {
		return this.address22;
	}

	public void setAddress22(String address22) {
		this.address22 = address22;
	}

	@Column(name = "CITY2", nullable = false, length = 24)
	public String getCity2() {
		return this.city2;
	}

	public void setCity2(String city2) {
		this.city2 = city2;
	}

	@Column(name = "STATE2", nullable = false, length = 24)
	public String getState2() {
		return this.state2;
	}

	public void setState2(String state2) {
		this.state2 = state2;
	}

	@Column(name = "ZIP2", nullable = false, length = 24)
	public String getZip2() {
		return this.zip2;
	}

	public void setZip2(String zip2) {
		this.zip2 = zip2;
	}

	@Column(name = "COUNTRY2", nullable = false, length = 24)
	public String getCountry2() {
		return this.country2;
	}

	public void setCountry2(String country2) {
		this.country2 = country2;
	}

	@Column(name = "MAILTO", nullable = false)
	public int getMailto() {
		return this.mailto;
	}

	public void setMailto(int mailto) {
		this.mailto = mailto;
	}

	@Column(name = "HPHONE", nullable = false, length = 24)
	public String getHphone() {
		return this.hphone;
	}

	public void setHphone(String hphone) {
		this.hphone = hphone;
	}

	@Column(name = "WPHONE1", nullable = false, length = 24)
	public String getWphone1() {
		return this.wphone1;
	}

	public void setWphone1(String wphone1) {
		this.wphone1 = wphone1;
	}

	@Column(name = "WPHONE2", nullable = false, length = 24)
	public String getWphone2() {
		return this.wphone2;
	}

	public void setWphone2(String wphone2) {
		this.wphone2 = wphone2;
	}

	@Column(name = "MPHONE", nullable = false, length = 24)
	public String getMphone() {
		return this.mphone;
	}

	public void setMphone(String mphone) {
		this.mphone = mphone;
	}

	@Column(name = "PHONETO", nullable = false)
	public int getPhoneto() {
		return this.phoneto;
	}

	public void setPhoneto(int phoneto) {
		this.phoneto = phoneto;
	}

	@Column(name = "FAX1", nullable = false, length = 24)
	public String getFax1() {
		return this.fax1;
	}

	public void setFax1(String fax1) {
		this.fax1 = fax1;
	}

	@Column(name = "FAX2", nullable = false, length = 24)
	public String getFax2() {
		return this.fax2;
	}

	public void setFax2(String fax2) {
		this.fax2 = fax2;
	}

	@Column(name = "EMAIL1", nullable = false, length = 72)
	public String getEmail1() {
		return this.email1;
	}

	public void setEmail1(String email1) {
		this.email1 = email1;
	}

	@Column(name = "EMAIL2", nullable = false, length = 72)
	public String getEmail2() {
		return this.email2;
	}

	public void setEmail2(String email2) {
		this.email2 = email2;
	}

	@Column(name = "EMAILTO", nullable = false)
	public int getEmailto() {
		return this.emailto;
	}

	public void setEmailto(int emailto) {
		this.emailto = emailto;
	}

	@Column(name = "URL", nullable = false, length = 150)
	public String getUrl() {
		return this.url;
	}

	public void setUrl(String url) {
		this.url = url;
	}

	@Column(name = "ACUITY", nullable = false)
	public byte getAcuity() {
		return this.acuity;
	}

	public void setAcuity(byte acuity) {
		this.acuity = acuity;
	}

	@Column(name = "PRICONTACT", nullable = false, length = 14)
	public String getPricontact() {
		return this.pricontact;
	}

	public void setPricontact(String pricontact) {
		this.pricontact = pricontact;
	}

	@Column(name = "CATEGORY", nullable = false, length = 24)
	public String getCategory() {
		return this.category;
	}

	public void setCategory(String category) {
		this.category = category;
	}

	@Column(name = "COMMENTS", nullable = false, length = 65535)
	public String getComments() {
		return this.comments;
	}

	public void setComments(String comments) {
		this.comments = comments;
	}

	@Column(name = "ABSTRACT", nullable = false, length = 65535)
	public String getAbstract_() {
		return this.abstract_;
	}

	public void setAbstract_(String abstract_) {
		this.abstract_ = abstract_;
	}

	@Column(name = "AUDIT", nullable = false, length = 65535)
	public String getAudit() {
		return this.audit;
	}

	public void setAudit(String audit) {
		this.audit = audit;
	}

	@Column(name = "ACTIVE", nullable = false)
	public boolean isActive() {
		return this.active;
	}

	public void setActive(boolean active) {
		this.active = active;
	}

	@Column(name = "DIRID", nullable = false, length = 24)
	public String getDirid() {
		return this.dirid;
	}

	public void setDirid(String dirid) {
		this.dirid = dirid;
	}

	@Column(name = "IMPORT", nullable = false, length = 24)
	public String getImport_() {
		return this.import_;
	}

	public void setImport_(String import_) {
		this.import_ = import_;
	}

	@Column(name = "DOB", nullable = false, length = 8)
	public String getDob() {
		return this.dob;
	}

	public void setDob(String dob) {
		this.dob = dob;
	}

	@Column(name = "DOA", nullable = false, length = 8)
	public String getDoa() {
		return this.doa;
	}

	public void setDoa(String doa) {
		this.doa = doa;
	}

	@Column(name = "EDOA", nullable = false, length = 8)
	public String getEdoa() {
		return this.edoa;
	}

	public void setEdoa(String edoa) {
		this.edoa = edoa;
	}

	@Column(name = "DOD", nullable = false, length = 8)
	public String getDod() {
		return this.dod;
	}

	public void setDod(String dod) {
		this.dod = dod;
	}

	@Column(name = "EDOD", nullable = false, length = 8)
	public String getEdod() {
		return this.edod;
	}

	public void setEdod(String edod) {
		this.edod = edod;
	}

	@Column(name = "INITIALCONTACT", nullable = false, length = 8)
	public String getInitialcontact() {
		return this.initialcontact;
	}

	public void setInitialcontact(String initialcontact) {
		this.initialcontact = initialcontact;
	}

	@Column(name = "ETHNIC", nullable = false, length = 24)
	public String getEthnic() {
		return this.ethnic;
	}

	public void setEthnic(String ethnic) {
		this.ethnic = ethnic;
	}

	@Column(name = "RELIGION", nullable = false, length = 254)
	public String getReligion() {
		return this.religion;
	}

	public void setReligion(String religion) {
		this.religion = religion;
	}

	@Column(name = "LIVESWITH", nullable = false, length = 72)
	public String getLiveswith() {
		return this.liveswith;
	}

	public void setLiveswith(String liveswith) {
		this.liveswith = liveswith;
	}

	@Column(name = "SSNUM", nullable = false, length = 24)
	public String getSsnum() {
		return this.ssnum;
	}

	public void setSsnum(String ssnum) {
		this.ssnum = ssnum;
	}

	@Column(name = "PROVIDER", nullable = false, length = 24)
	public String getProvider() {
		return this.provider;
	}

	public void setProvider(String provider) {
		this.provider = provider;
	}

	@Column(name = "PROVIDER2", nullable = false, length = 24)
	public String getProvider2() {
		return this.provider2;
	}

	public void setProvider2(String provider2) {
		this.provider2 = provider2;
	}

	@Column(name = "PROVIDER3", nullable = false, length = 24)
	public String getProvider3() {
		return this.provider3;
	}

	public void setProvider3(String provider3) {
		this.provider3 = provider3;
	}

	@Column(name = "PROVIDER4", nullable = false, length = 24)
	public String getProvider4() {
		return this.provider4;
	}

	public void setProvider4(String provider4) {
		this.provider4 = provider4;
	}

	@Column(name = "ALTID", nullable = false, length = 254)
	public String getAltid() {
		return this.altid;
	}

	public void setAltid(String altid) {
		this.altid = altid;
	}

	@Column(name = "GLOBALID", nullable = false, length = 254)
	public String getGlobalid() {
		return this.globalid;
	}

	public void setGlobalid(String globalid) {
		this.globalid = globalid;
	}

	@Column(name = "PGROUP", nullable = false, length = 24)
	public String getPgroup() {
		return this.pgroup;
	}

	public void setPgroup(String pgroup) {
		this.pgroup = pgroup;
	}

	@Column(name = "SCHOOL", nullable = false, length = 72)
	public String getSchool() {
		return this.school;
	}

	public void setSchool(String school) {
		this.school = school;
	}

	@Column(name = "GRADE", nullable = false, length = 24)
	public String getGrade() {
		return this.grade;
	}

	public void setGrade(String grade) {
		this.grade = grade;
	}

	@Column(name = "LUPDATE", nullable = false, length = 14)
	public String getLupdate() {
		return this.lupdate;
	}

	public void setLupdate(String lupdate) {
		this.lupdate = lupdate;
	}

	@Column(name = "LOCATION", nullable = false, length = 65535)
	public String getLocation() {
		return this.location;
	}

	public void setLocation(String location) {
		this.location = location;
	}

	@Column(name = "REFERRER", nullable = false, length = 254)
	public String getReferrer() {
		return this.referrer;
	}

	public void setReferrer(String referrer) {
		this.referrer = referrer;
	}

	@Column(name = "SALUTATION", nullable = false, length = 254)
	public String getSalutation() {
		return this.salutation;
	}

	public void setSalutation(String salutation) {
		this.salutation = salutation;
	}

	@Column(name = "QUALIFIED", nullable = false)
	public boolean isQualified() {
		return this.qualified;
	}

	public void setQualified(boolean qualified) {
		this.qualified = qualified;
	}

	@Column(name = "INACTIVE_REASON", nullable = false, length = 254)
	public String getInactiveReason() {
		return this.inactiveReason;
	}

	public void setInactiveReason(String inactiveReason) {
		this.inactiveReason = inactiveReason;
	}

	@Column(name = "PIN", nullable = false, length = 24)
	public String getPin() {
		return this.pin;
	}

	public void setPin(String pin) {
		this.pin = pin;
	}

	@Column(name = "BNID", nullable = false, length = 24)
	public String getBnid() {
		return this.bnid;
	}

	public void setBnid(String bnid) {
		this.bnid = bnid;
	}

	@Column(name = "READONLY", nullable = false)
	public byte getReadonly() {
		return this.readonly;
	}

	public void setReadonly(byte readonly) {
		this.readonly = readonly;
	}

	@Column(name = "UNDELETEABLE", nullable = false)
	public byte getUndeleteable() {
		return this.undeleteable;
	}

	public void setUndeleteable(byte undeleteable) {
		this.undeleteable = undeleteable;
	}

	@Column(name = "FEE_SCHEDULE", nullable = false)
	public int getFeeSchedule() {
		return this.feeSchedule;
	}

	public void setFeeSchedule(int feeSchedule) {
		this.feeSchedule = feeSchedule;
	}

	@Column(name = "TRANSGENDER", nullable = false)
	public int getTransgender() {
		return this.transgender;
	}

	public void setTransgender(int transgender) {
		this.transgender = transgender;
	}

	@Column(name = "facilityId", nullable = false)
	public int getFacilityId() {
		return this.facilityId;
	}

	public void setFacilityId(int facilityId) {
		this.facilityId = facilityId;
	}

	@Column(name = "cashOnly", nullable = false, length = 1)
	public String getCashOnly() {
		return this.cashOnly;
	}

	public void setCashOnly(String cashOnly) {
		this.cashOnly = cashOnly;
	}

	@Column(name = "ethnicityId", nullable = false)
	public int getEthnicityId() {
		return this.ethnicityId;
	}

	public void setEthnicityId(int ethnicityId) {
		this.ethnicityId = ethnicityId;
	}

	@Column(name = "smokingStatusId", nullable = false)
	public int getSmokingStatusId() {
		return this.smokingStatusId;
	}

	public void setSmokingStatusId(int smokingStatusId) {
		this.smokingStatusId = smokingStatusId;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "smokingStatusDate", nullable = false, length = 0)
	public Date getSmokingStatusDate() {
		return this.smokingStatusDate;
	}

	public void setSmokingStatusDate(Date smokingStatusDate) {
		this.smokingStatusDate = smokingStatusDate;
	}

	@Column(name = "MOTHER_MAIDEN_NAME", nullable = false, length = 254)
	public String getMotherMaidenName() {
		return this.motherMaidenName;
	}

	public void setMotherMaidenName(String motherMaidenName) {
		this.motherMaidenName = motherMaidenName;
	}

	@Column(name = "maritalStatusCode", nullable = false, length = 10)
	public String getMaritalStatusCode() {
		return this.maritalStatusCode;
	}

	public void setMaritalStatusCode(String maritalStatusCode) {
		this.maritalStatusCode = maritalStatusCode;
	}

	@Column(name = "languageCode", nullable = false, length = 10)
	public String getLanguageCode() {
		return this.languageCode;
	}

	public void setLanguageCode(String languageCode) {
		this.languageCode = languageCode;
	}

	@Column(name = "communicationPreference", nullable = false, length = 10)
	public String getCommunicationPreference() {
		return this.communicationPreference;
	}

	public void setCommunicationPreference(String communicationPreference) {
		this.communicationPreference = communicationPreference;
	}

	@Column(name = "nextOfKin", length = 20)
	public String getNextOfKin() {
		return this.nextOfKin;
	}

	public void setNextOfKin(String nextOfKin) {
		this.nextOfKin = nextOfKin;
	}

	@Column(name = "MPI", nullable = false)
	public int getMpi() {
		return this.mpi;
	}

	public void setMpi(int mpi) {
		this.mpi = mpi;
	}

}
