package com.cantatahealth.fhir.db.model;
// Generated Oct 31, 2017 5:51:36 PM by Hibernate Tools 4.3.1.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * AllergyIntoleranceMapDbEntity generated by hbm2java
 */
@Entity
@Table(name = "AllergyIntoleranceMap", schema = "dbo", catalog = "FHIRDB")
public class AllergyIntoleranceMapDbEntity implements java.io.Serializable {

	private long id;
	private AllergyIntoleranceDbEntity allergyIntoleranceDbEntity;
	private PractitionerDbEntity practitionerDbEntity;
	private ReactionnDbEntity reactionnDbEntity;

	public AllergyIntoleranceMapDbEntity() {
	}

	public AllergyIntoleranceMapDbEntity(long id, AllergyIntoleranceDbEntity allergyIntoleranceDbEntity) {
		this.id = id;
		this.allergyIntoleranceDbEntity = allergyIntoleranceDbEntity;
	}

	public AllergyIntoleranceMapDbEntity(long id, AllergyIntoleranceDbEntity allergyIntoleranceDbEntity,
			PractitionerDbEntity practitionerDbEntity, ReactionnDbEntity reactionnDbEntity) {
		this.id = id;
		this.allergyIntoleranceDbEntity = allergyIntoleranceDbEntity;
		this.practitionerDbEntity = practitionerDbEntity;
		this.reactionnDbEntity = reactionnDbEntity;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false, precision = 18, scale = 0)
	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "allergyintolerance", nullable = false)
	public AllergyIntoleranceDbEntity getAllergyIntoleranceDbEntity() {
		return this.allergyIntoleranceDbEntity;
	}

	public void setAllergyIntoleranceDbEntity(AllergyIntoleranceDbEntity allergyIntoleranceDbEntity) {
		this.allergyIntoleranceDbEntity = allergyIntoleranceDbEntity;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "practitioner")
	public PractitionerDbEntity getPractitionerDbEntity() {
		return this.practitionerDbEntity;
	}

	public void setPractitionerDbEntity(PractitionerDbEntity practitionerDbEntity) {
		this.practitionerDbEntity = practitionerDbEntity;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "reaction")
	public ReactionnDbEntity getReactionnDbEntity() {
		return this.reactionnDbEntity;
	}

	public void setReactionnDbEntity(ReactionnDbEntity reactionnDbEntity) {
		this.reactionnDbEntity = reactionnDbEntity;
	}

}
