package com.cantatahealth.fhir.db.model;
// Generated Oct 31, 2017 5:51:36 PM by Hibernate Tools 4.3.1.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * AppointmentDbEntity generated by hbm2java
 */
@Entity
@Table(name = "Appointment", schema = "dbo", catalog = "FHIRDB")
public class AppointmentDbEntity implements java.io.Serializable {

	private long id;
	private Long identifier;
	private Integer priority;
	private String description;
	private Date start;
	private Date endAlias;
	private Integer minutesDuration;
	private Date created;
	private String comment;

	public AppointmentDbEntity() {
	}

	public AppointmentDbEntity(long id) {
		this.id = id;
	}

	public AppointmentDbEntity(long id, Long identifier, Integer priority, String description, Date start,
			Date endAlias, Integer minutesDuration, Date created, String comment) {
		this.id = id;
		this.identifier = identifier;
		this.priority = priority;
		this.description = description;
		this.start = start;
		this.endAlias = endAlias;
		this.minutesDuration = minutesDuration;
		this.created = created;
		this.comment = comment;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false, precision = 18, scale = 0)
	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	@Column(name = "identifier", precision = 18, scale = 0)
	public Long getIdentifier() {
		return this.identifier;
	}

	public void setIdentifier(Long identifier) {
		this.identifier = identifier;
	}

	@Column(name = "priority")
	public Integer getPriority() {
		return this.priority;
	}

	public void setPriority(Integer priority) {
		this.priority = priority;
	}

	@Column(name = "description")
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "start", length = 23)
	public Date getStart() {
		return this.start;
	}

	public void setStart(Date start) {
		this.start = start;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "end_alias", length = 23)
	public Date getEndAlias() {
		return this.endAlias;
	}

	public void setEndAlias(Date endAlias) {
		this.endAlias = endAlias;
	}

	@Column(name = "minutesDuration")
	public Integer getMinutesDuration() {
		return this.minutesDuration;
	}

	public void setMinutesDuration(Integer minutesDuration) {
		this.minutesDuration = minutesDuration;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "created", length = 23)
	public Date getCreated() {
		return this.created;
	}

	public void setCreated(Date created) {
		this.created = created;
	}

	@Column(name = "comment")
	public String getComment() {
		return this.comment;
	}

	public void setComment(String comment) {
		this.comment = comment;
	}

}
