package com.cantatahealth.fhir.db.model;
// Generated Oct 31, 2017 5:51:36 PM by Hibernate Tools 4.3.1.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * CareTeamMapDbEntity generated by hbm2java
 */
@Entity
@Table(name = "CareTeamMap", schema = "dbo", catalog = "FHIRDB")
public class CareTeamMapDbEntity implements java.io.Serializable {

	private long id;
	private CareTeamDbEntity careTeamDbEntity;
	private PractitionerDbEntity practitionerDbEntity;

	public CareTeamMapDbEntity() {
	}

	public CareTeamMapDbEntity(long id) {
		this.id = id;
	}

	public CareTeamMapDbEntity(long id, CareTeamDbEntity careTeamDbEntity, PractitionerDbEntity practitionerDbEntity) {
		this.id = id;
		this.careTeamDbEntity = careTeamDbEntity;
		this.practitionerDbEntity = practitionerDbEntity;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false, precision = 18, scale = 0)
	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CareTeam")
	public CareTeamDbEntity getCareTeamDbEntity() {
		return this.careTeamDbEntity;
	}

	public void setCareTeamDbEntity(CareTeamDbEntity careTeamDbEntity) {
		this.careTeamDbEntity = careTeamDbEntity;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "Practitioner")
	public PractitionerDbEntity getPractitionerDbEntity() {
		return this.practitionerDbEntity;
	}

	public void setPractitionerDbEntity(PractitionerDbEntity practitionerDbEntity) {
		this.practitionerDbEntity = practitionerDbEntity;
	}

}
