package com.cantatahealth.fhir.db.model;
// Generated Oct 31, 2017 5:51:36 PM by Hibernate Tools 4.3.1.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * CCDAMapDbEntity generated by hbm2java
 */
@Entity
@Table(name = "CCDAMap", schema = "dbo", catalog = "FHIRDB")
public class CCDAMapDbEntity implements java.io.Serializable {

	private long id;
	private Long coding;
	private String ccdacode;
	private String ccdasystem;

	public CCDAMapDbEntity() {
	}

	public CCDAMapDbEntity(long id) {
		this.id = id;
	}

	public CCDAMapDbEntity(long id, Long coding, String ccdacode, String ccdasystem) {
		this.id = id;
		this.coding = coding;
		this.ccdacode = ccdacode;
		this.ccdasystem = ccdasystem;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false, precision = 18, scale = 0)
	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	@Column(name = "coding", precision = 18, scale = 0)
	public Long getCoding() {
		return this.coding;
	}

	public void setCoding(Long coding) {
		this.coding = coding;
	}

	@Column(name = "ccdacode")
	public String getCcdacode() {
		return this.ccdacode;
	}

	public void setCcdacode(String ccdacode) {
		this.ccdacode = ccdacode;
	}

	@Column(name = "ccdasystem")
	public String getCcdasystem() {
		return this.ccdasystem;
	}

	public void setCcdasystem(String ccdasystem) {
		this.ccdasystem = ccdasystem;
	}

}
