package com.cantatahealth.fhir.db.model;
// Generated Sep 15, 2017 3:14:58 PM by Hibernate Tools 4.3.1.Final

import java.io.Serializable;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * CodeableConceptDbEntity generated by hbm2java
 */
@Entity
@Table(name = "CodeableConcept", schema = "dbo", catalog = "FHIRDB")
public class CodeableConceptDbEntity implements java.io.Serializable {

	private long id;
	private Serializable code;
	private Serializable text;
	private Serializable concept;
	private Date createddate;
	private Serializable createdby;
	private Date updateddate;
	private Serializable updatedby;

	public CodeableConceptDbEntity() {
	}

	public CodeableConceptDbEntity(long id) {
		this.id = id;
	}

	public CodeableConceptDbEntity(long id, Serializable code, Serializable text, Serializable concept,
			Date createddate, Serializable createdby, Date updateddate, Serializable updatedby) {
		this.id = id;
		this.code = code;
		this.text = text;
		this.concept = concept;
		this.createddate = createddate;
		this.createdby = createdby;
		this.updateddate = updateddate;
		this.updatedby = updatedby;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false, precision = 18, scale = 0)
	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	@Column(name = "code")
	public Serializable getCode() {
		return this.code;
	}

	public void setCode(Serializable code) {
		this.code = code;
	}

	@Column(name = "text")
	public Serializable getText() {
		return this.text;
	}

	public void setText(Serializable text) {
		this.text = text;
	}

	@Column(name = "concept")
	public Serializable getConcept() {
		return this.concept;
	}

	public void setConcept(Serializable concept) {
		this.concept = concept;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "createddate", length = 23)
	public Date getCreateddate() {
		return this.createddate;
	}

	public void setCreateddate(Date createddate) {
		this.createddate = createddate;
	}

	@Column(name = "createdby")
	public Serializable getCreatedby() {
		return this.createdby;
	}

	public void setCreatedby(Serializable createdby) {
		this.createdby = createdby;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "updateddate", length = 23)
	public Date getUpdateddate() {
		return this.updateddate;
	}

	public void setUpdateddate(Date updateddate) {
		this.updateddate = updateddate;
	}

	@Column(name = "updatedby")
	public Serializable getUpdatedby() {
		return this.updatedby;
	}

	public void setUpdatedby(Serializable updatedby) {
		this.updatedby = updatedby;
	}

}
