package com.cantatahealth.fhir.db.model;
// Generated Sep 28, 2017 4:59:08 PM by Hibernate Tools 4.3.1.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * ConditionMapDbEntity generated by hbm2java
 */
@Entity
@Table(name = "ConditionMap", schema = "dbo", catalog = "FHIRDB")
public class ConditionMapDbEntity implements java.io.Serializable {

	private long id;
	private ConditionDbEntity conditionDbEntity;
	private PractitionerDbEntity practitionerDbEntity;

	public ConditionMapDbEntity() {
	}

	public ConditionMapDbEntity(long id) {
		this.id = id;
	}

	public ConditionMapDbEntity(long id, ConditionDbEntity conditionDbEntity,
			PractitionerDbEntity practitionerDbEntity) {
		this.id = id;
		this.conditionDbEntity = conditionDbEntity;
		this.practitionerDbEntity = practitionerDbEntity;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false, precision = 18, scale = 0)
	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "condition")
	public ConditionDbEntity getConditionDbEntity() {
		return this.conditionDbEntity;
	}

	public void setConditionDbEntity(ConditionDbEntity conditionDbEntity) {
		this.conditionDbEntity = conditionDbEntity;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "practitioner")
	public PractitionerDbEntity getPractitionerDbEntity() {
		return this.practitionerDbEntity;
	}

	public void setPractitionerDbEntity(PractitionerDbEntity practitionerDbEntity) {
		this.practitionerDbEntity = practitionerDbEntity;
	}

}
