package com.cantatahealth.fhir.db.model;
// Generated Oct 31, 2017 5:51:36 PM by Hibernate Tools 4.3.1.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * ContactPointDbEntity generated by hbm2java
 */
@Entity
@Table(name = "ContactPoint", schema = "dbo", catalog = "FHIRDB")
public class ContactPointDbEntity implements java.io.Serializable {

	private long id;
	private String system;
	private String value;
	private String useAlias;
	private Short rank;
	private Date createddate;
	private String createdby;
	private Date updateddate;
	private String updatedby;
	private Boolean active;
	private Set<PractitionerMapDbEntity> practitionerMapDbEntities = new HashSet<PractitionerMapDbEntity>(0);
	private Set<PatientMapDbEntity> patientMapDbEntities = new HashSet<PatientMapDbEntity>(0);
	private Set<LocationMapDbEntity> locationMapDbEntities = new HashSet<LocationMapDbEntity>(0);
	private Set<RelatedPersonDbEntity> relatedPersonDbEntities = new HashSet<RelatedPersonDbEntity>(0);
	private Set<LocationMapDbEntity> locationMapDbEntities_1 = new HashSet<LocationMapDbEntity>(0);
	private Set<RelatedPersonDbEntity> relatedPersonDbEntities_1 = new HashSet<RelatedPersonDbEntity>(0);

	public ContactPointDbEntity() {
	}

	public ContactPointDbEntity(long id) {
		this.id = id;
	}

	public ContactPointDbEntity(long id, String system, String value, String useAlias, Short rank, Date createddate,
			String createdby, Date updateddate, String updatedby, Boolean active,
			Set<PractitionerMapDbEntity> practitionerMapDbEntities, Set<PatientMapDbEntity> patientMapDbEntities,
			Set<LocationMapDbEntity> locationMapDbEntities, Set<RelatedPersonDbEntity> relatedPersonDbEntities,
			Set<LocationMapDbEntity> locationMapDbEntities_1, Set<RelatedPersonDbEntity> relatedPersonDbEntities_1) {
		this.id = id;
		this.system = system;
		this.value = value;
		this.useAlias = useAlias;
		this.rank = rank;
		this.createddate = createddate;
		this.createdby = createdby;
		this.updateddate = updateddate;
		this.updatedby = updatedby;
		this.active = active;
		this.practitionerMapDbEntities = practitionerMapDbEntities;
		this.patientMapDbEntities = patientMapDbEntities;
		this.locationMapDbEntities = locationMapDbEntities;
		this.relatedPersonDbEntities = relatedPersonDbEntities;
		this.locationMapDbEntities_1 = locationMapDbEntities_1;
		this.relatedPersonDbEntities_1 = relatedPersonDbEntities_1;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false, precision = 18, scale = 0)
	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	@Column(name = "system")
	public String getSystem() {
		return this.system;
	}

	public void setSystem(String system) {
		this.system = system;
	}

	@Column(name = "value")
	public String getValue() {
		return this.value;
	}

	public void setValue(String value) {
		this.value = value;
	}

	@Column(name = "use_alias")
	public String getUseAlias() {
		return this.useAlias;
	}

	public void setUseAlias(String useAlias) {
		this.useAlias = useAlias;
	}

	@Column(name = "rank")
	public Short getRank() {
		return this.rank;
	}

	public void setRank(Short rank) {
		this.rank = rank;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "createddate", length = 23)
	public Date getCreateddate() {
		return this.createddate;
	}

	public void setCreateddate(Date createddate) {
		this.createddate = createddate;
	}

	@Column(name = "createdby")
	public String getCreatedby() {
		return this.createdby;
	}

	public void setCreatedby(String createdby) {
		this.createdby = createdby;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "updateddate", length = 23)
	public Date getUpdateddate() {
		return this.updateddate;
	}

	public void setUpdateddate(Date updateddate) {
		this.updateddate = updateddate;
	}

	@Column(name = "updatedby")
	public String getUpdatedby() {
		return this.updatedby;
	}

	public void setUpdatedby(String updatedby) {
		this.updatedby = updatedby;
	}

	@Column(name = "active")
	public Boolean getActive() {
		return this.active;
	}

	public void setActive(Boolean active) {
		this.active = active;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "contactPointDbEntity")
	public Set<PractitionerMapDbEntity> getPractitionerMapDbEntities() {
		return this.practitionerMapDbEntities;
	}

	public void setPractitionerMapDbEntities(Set<PractitionerMapDbEntity> practitionerMapDbEntities) {
		this.practitionerMapDbEntities = practitionerMapDbEntities;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "contactPointDbEntity")
	public Set<PatientMapDbEntity> getPatientMapDbEntities() {
		return this.patientMapDbEntities;
	}

	public void setPatientMapDbEntities(Set<PatientMapDbEntity> patientMapDbEntities) {
		this.patientMapDbEntities = patientMapDbEntities;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "contactPointDbEntity")
	public Set<LocationMapDbEntity> getLocationMapDbEntities() {
		return this.locationMapDbEntities;
	}

	public void setLocationMapDbEntities(Set<LocationMapDbEntity> locationMapDbEntities) {
		this.locationMapDbEntities = locationMapDbEntities;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "contactPointDbEntity")
	public Set<RelatedPersonDbEntity> getRelatedPersonDbEntities() {
		return this.relatedPersonDbEntities;
	}

	public void setRelatedPersonDbEntities(Set<RelatedPersonDbEntity> relatedPersonDbEntities) {
		this.relatedPersonDbEntities = relatedPersonDbEntities;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "contactPointDbEntity")
	public Set<LocationMapDbEntity> getLocationMapDbEntities_1() {
		return this.locationMapDbEntities_1;
	}

	public void setLocationMapDbEntities_1(Set<LocationMapDbEntity> locationMapDbEntities_1) {
		this.locationMapDbEntities_1 = locationMapDbEntities_1;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "contactPointDbEntity")
	public Set<RelatedPersonDbEntity> getRelatedPersonDbEntities_1() {
		return this.relatedPersonDbEntities_1;
	}

	public void setRelatedPersonDbEntities_1(Set<RelatedPersonDbEntity> relatedPersonDbEntities_1) {
		this.relatedPersonDbEntities_1 = relatedPersonDbEntities_1;
	}

}
