package com.cantatahealth.fhir.db.model;
// Generated Oct 31, 2017 5:51:36 PM by Hibernate Tools 4.3.1.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Version;

/**
 * DeviceDbEntity generated by hbm2java
 */
@Entity
@Table(name = "Device", schema = "dbo", catalog = "FHIRDB")
public class DeviceDbEntity implements java.io.Serializable {

	private long id;
	private String version;
	private CodingDbEntity codingDbEntityByStatus;
	private CodingDbEntity codingDbEntityByType;
	private OrganizationDbEntity organizationDbEntity;
	private PatientDbEntity patientDbEntity;
	private String carrierhrf;
	private String deviceidentifier;
	private String name;
	private String issuer;
	private String lotnumber;
	private String manufacturer;
	private Date manufacturedate;
	private Date expirationdate;
	private String model;
	private String note;

	public DeviceDbEntity() {
	}

	public DeviceDbEntity(long id, OrganizationDbEntity organizationDbEntity) {
		this.id = id;
		this.organizationDbEntity = organizationDbEntity;
	}

	public DeviceDbEntity(long id, CodingDbEntity codingDbEntityByStatus, CodingDbEntity codingDbEntityByType,
			OrganizationDbEntity organizationDbEntity, PatientDbEntity patientDbEntity, String carrierhrf,
			String deviceidentifier, String name, String issuer, String lotnumber, String manufacturer,
			Date manufacturedate, Date expirationdate, String model, String note) {
		this.id = id;
		this.codingDbEntityByStatus = codingDbEntityByStatus;
		this.codingDbEntityByType = codingDbEntityByType;
		this.organizationDbEntity = organizationDbEntity;
		this.patientDbEntity = patientDbEntity;
		this.carrierhrf = carrierhrf;
		this.deviceidentifier = deviceidentifier;
		this.name = name;
		this.issuer = issuer;
		this.lotnumber = lotnumber;
		this.manufacturer = manufacturer;
		this.manufacturedate = manufacturedate;
		this.expirationdate = expirationdate;
		this.model = model;
		this.note = note;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false, precision = 18, scale = 0)
	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}


	@Column(name = "version")
	public String getVersion() {
		return this.version;
	}

	public void setVersion(String version) {
		this.version = version;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "status")
	public CodingDbEntity getCodingDbEntityByStatus() {
		return this.codingDbEntityByStatus;
	}

	public void setCodingDbEntityByStatus(CodingDbEntity codingDbEntityByStatus) {
		this.codingDbEntityByStatus = codingDbEntityByStatus;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "type")
	public CodingDbEntity getCodingDbEntityByType() {
		return this.codingDbEntityByType;
	}

	public void setCodingDbEntityByType(CodingDbEntity codingDbEntityByType) {
		this.codingDbEntityByType = codingDbEntityByType;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "owner", nullable = false)
	public OrganizationDbEntity getOrganizationDbEntity() {
		return this.organizationDbEntity;
	}

	public void setOrganizationDbEntity(OrganizationDbEntity organizationDbEntity) {
		this.organizationDbEntity = organizationDbEntity;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "patient")
	public PatientDbEntity getPatientDbEntity() {
		return this.patientDbEntity;
	}

	public void setPatientDbEntity(PatientDbEntity patientDbEntity) {
		this.patientDbEntity = patientDbEntity;
	}

	@Column(name = "carrierhrf")
	public String getCarrierhrf() {
		return this.carrierhrf;
	}

	public void setCarrierhrf(String carrierhrf) {
		this.carrierhrf = carrierhrf;
	}

	@Column(name = "deviceidentifier")
	public String getDeviceidentifier() {
		return this.deviceidentifier;
	}

	public void setDeviceidentifier(String deviceidentifier) {
		this.deviceidentifier = deviceidentifier;
	}

	@Column(name = "name")
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "issuer")
	public String getIssuer() {
		return this.issuer;
	}

	public void setIssuer(String issuer) {
		this.issuer = issuer;
	}

	@Column(name = "lotnumber")
	public String getLotnumber() {
		return this.lotnumber;
	}

	public void setLotnumber(String lotnumber) {
		this.lotnumber = lotnumber;
	}

	@Column(name = "manufacturer")
	public String getManufacturer() {
		return this.manufacturer;
	}

	public void setManufacturer(String manufacturer) {
		this.manufacturer = manufacturer;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "manufacturedate", length = 23)
	public Date getManufacturedate() {
		return this.manufacturedate;
	}

	public void setManufacturedate(Date manufacturedate) {
		this.manufacturedate = manufacturedate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "expirationdate", length = 23)
	public Date getExpirationdate() {
		return this.expirationdate;
	}

	public void setExpirationdate(Date expirationdate) {
		this.expirationdate = expirationdate;
	}

	@Column(name = "model")
	public String getModel() {
		return this.model;
	}

	public void setModel(String model) {
		this.model = model;
	}

	@Column(name = "note")
	public String getNote() {
		return this.note;
	}

	public void setNote(String note) {
		this.note = note;
	}

}
