package com.cantatahealth.fhir.db.model;
// Generated Oct 31, 2017 5:51:36 PM by Hibernate Tools 4.3.1.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * DosageDbEntity generated by hbm2java
 */
@Entity
@Table(name = "Dosage", schema = "dbo", catalog = "FHIRDB")
public class DosageDbEntity implements java.io.Serializable {

	private long id;
	private CodingDbEntity codingDbEntity;
	private QuantityDbEntity quantityDbEntity;
	private String text;
	private Set<MedicationAdministrationDbEntity> medicationAdministrationDbEntities = new HashSet<MedicationAdministrationDbEntity>(
			0);

	public DosageDbEntity() {
	}

	public DosageDbEntity(long id) {
		this.id = id;
	}

	public DosageDbEntity(long id, CodingDbEntity codingDbEntity, QuantityDbEntity quantityDbEntity, String text,
			Set<MedicationAdministrationDbEntity> medicationAdministrationDbEntities) {
		this.id = id;
		this.codingDbEntity = codingDbEntity;
		this.quantityDbEntity = quantityDbEntity;
		this.text = text;
		this.medicationAdministrationDbEntities = medicationAdministrationDbEntities;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false, precision = 18, scale = 0)
	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "route")
	public CodingDbEntity getCodingDbEntity() {
		return this.codingDbEntity;
	}

	public void setCodingDbEntity(CodingDbEntity codingDbEntity) {
		this.codingDbEntity = codingDbEntity;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "dose")
	public QuantityDbEntity getQuantityDbEntity() {
		return this.quantityDbEntity;
	}

	public void setQuantityDbEntity(QuantityDbEntity quantityDbEntity) {
		this.quantityDbEntity = quantityDbEntity;
	}

	@Column(name = "text")
	public String getText() {
		return this.text;
	}

	public void setText(String text) {
		this.text = text;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "dosageDbEntity")
	public Set<MedicationAdministrationDbEntity> getMedicationAdministrationDbEntities() {
		return this.medicationAdministrationDbEntities;
	}

	public void setMedicationAdministrationDbEntities(
			Set<MedicationAdministrationDbEntity> medicationAdministrationDbEntities) {
		this.medicationAdministrationDbEntities = medicationAdministrationDbEntities;
	}

}
