package com.cantatahealth.fhir.db.model;
// Generated Oct 31, 2017 5:51:36 PM by Hibernate Tools 4.3.1.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * ExtensionDbEntity generated by hbm2java
 */
@Entity
@Table(name = "Extension", schema = "dbo", catalog = "FHIRDB")
public class ExtensionDbEntity implements java.io.Serializable {

	private long id;
	private String name;
	private String url;
	private Long resource;

	public ExtensionDbEntity() {
	}

	public ExtensionDbEntity(long id) {
		this.id = id;
	}

	public ExtensionDbEntity(long id, String name, String url, Long resource) {
		this.id = id;
		this.name = name;
		this.url = url;
		this.resource = resource;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false, precision = 18, scale = 0)
	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	@Column(name = "name")
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "url")
	public String getUrl() {
		return this.url;
	}

	public void setUrl(String url) {
		this.url = url;
	}

	@Column(name = "resource", precision = 18, scale = 0)
	public Long getResource() {
		return this.resource;
	}

	public void setResource(Long resource) {
		this.resource = resource;
	}

}
