package com.cantatahealth.fhir.db.model;
// Generated Oct 31, 2017 5:51:36 PM by Hibernate Tools 4.3.1.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * GoalMapDbEntity generated by hbm2java
 */
@Entity
@Table(name = "GoalMap", schema = "dbo", catalog = "FHIRDB")
public class GoalMapDbEntity implements java.io.Serializable {

	private long id;
	private ConditionDbEntity conditionDbEntity;
	private GoalDbEntity goalDbEntity;
	private ObservationDbEntity observationDbEntity;

	public GoalMapDbEntity() {
	}

	public GoalMapDbEntity(long id) {
		this.id = id;
	}

	public GoalMapDbEntity(long id, ConditionDbEntity conditionDbEntity, GoalDbEntity goalDbEntity,
			ObservationDbEntity observationDbEntity) {
		this.id = id;
		this.conditionDbEntity = conditionDbEntity;
		this.goalDbEntity = goalDbEntity;
		this.observationDbEntity = observationDbEntity;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false, precision = 18, scale = 0)
	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "condition")
	public ConditionDbEntity getConditionDbEntity() {
		return this.conditionDbEntity;
	}

	public void setConditionDbEntity(ConditionDbEntity conditionDbEntity) {
		this.conditionDbEntity = conditionDbEntity;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "goal")
	public GoalDbEntity getGoalDbEntity() {
		return this.goalDbEntity;
	}

	public void setGoalDbEntity(GoalDbEntity goalDbEntity) {
		this.goalDbEntity = goalDbEntity;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "observation")
	public ObservationDbEntity getObservationDbEntity() {
		return this.observationDbEntity;
	}

	public void setObservationDbEntity(ObservationDbEntity observationDbEntity) {
		this.observationDbEntity = observationDbEntity;
	}

}
