package com.cantatahealth.fhir.db.model;
// Generated Oct 31, 2017 5:51:36 PM by Hibernate Tools 4.3.1.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * HumanNameDbEntity generated by hbm2java
 */
@Entity
@Table(name = "HumanName", schema = "dbo", catalog = "FHIRDB")
public class HumanNameDbEntity implements java.io.Serializable {

	private long id;
	private String useAlias;
	private String family;
	private String given;
	private String prefix;
	private String suffix;
	private String active;
	private Date createddate;
	private String createdby;
	private Date updateddate;
	private String updatedby;
	private Set<RelatedPersonDbEntity> relatedPersonDbEntities = new HashSet<RelatedPersonDbEntity>(0);
	private Set<PatientMapDbEntity> patientMapDbEntities = new HashSet<PatientMapDbEntity>(0);
	private Set<PractitionerMapDbEntity> practitionerMapDbEntities = new HashSet<PractitionerMapDbEntity>(0);

	public HumanNameDbEntity() {
	}

	public HumanNameDbEntity(long id) {
		this.id = id;
	}

	public HumanNameDbEntity(long id, String useAlias, String family, String given, String prefix, String suffix,
			String active, Date createddate, String createdby, Date updateddate, String updatedby,
			Set<RelatedPersonDbEntity> relatedPersonDbEntities, Set<PatientMapDbEntity> patientMapDbEntities,
			Set<PractitionerMapDbEntity> practitionerMapDbEntities) {
		this.id = id;
		this.useAlias = useAlias;
		this.family = family;
		this.given = given;
		this.prefix = prefix;
		this.suffix = suffix;
		this.active = active;
		this.createddate = createddate;
		this.createdby = createdby;
		this.updateddate = updateddate;
		this.updatedby = updatedby;
		this.relatedPersonDbEntities = relatedPersonDbEntities;
		this.patientMapDbEntities = patientMapDbEntities;
		this.practitionerMapDbEntities = practitionerMapDbEntities;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false, precision = 18, scale = 0)
	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	@Column(name = "use_alias")
	public String getUseAlias() {
		return this.useAlias;
	}

	public void setUseAlias(String useAlias) {
		this.useAlias = useAlias;
	}

	@Column(name = "family")
	public String getFamily() {
		return this.family;
	}

	public void setFamily(String family) {
		this.family = family;
	}

	@Column(name = "given")
	public String getGiven() {
		return this.given;
	}

	public void setGiven(String given) {
		this.given = given;
	}

	@Column(name = "prefix")
	public String getPrefix() {
		return this.prefix;
	}

	public void setPrefix(String prefix) {
		this.prefix = prefix;
	}

	@Column(name = "suffix")
	public String getSuffix() {
		return this.suffix;
	}

	public void setSuffix(String suffix) {
		this.suffix = suffix;
	}

	@Column(name = "active")
	public String getActive() {
		return this.active;
	}

	public void setActive(String active) {
		this.active = active;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "createddate", length = 23)
	public Date getCreateddate() {
		return this.createddate;
	}

	public void setCreateddate(Date createddate) {
		this.createddate = createddate;
	}

	@Column(name = "createdby")
	public String getCreatedby() {
		return this.createdby;
	}

	public void setCreatedby(String createdby) {
		this.createdby = createdby;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "updateddate", length = 23)
	public Date getUpdateddate() {
		return this.updateddate;
	}

	public void setUpdateddate(Date updateddate) {
		this.updateddate = updateddate;
	}

	@Column(name = "updatedby")
	public String getUpdatedby() {
		return this.updatedby;
	}

	public void setUpdatedby(String updatedby) {
		this.updatedby = updatedby;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "humanNameDbEntity")
	public Set<RelatedPersonDbEntity> getRelatedPersonDbEntities() {
		return this.relatedPersonDbEntities;
	}

	public void setRelatedPersonDbEntities(Set<RelatedPersonDbEntity> relatedPersonDbEntities) {
		this.relatedPersonDbEntities = relatedPersonDbEntities;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "humanNameDbEntity")
	public Set<PatientMapDbEntity> getPatientMapDbEntities() {
		return this.patientMapDbEntities;
	}

	public void setPatientMapDbEntities(Set<PatientMapDbEntity> patientMapDbEntities) {
		this.patientMapDbEntities = patientMapDbEntities;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "humanNameDbEntity")
	public Set<PractitionerMapDbEntity> getPractitionerMapDbEntities() {
		return this.practitionerMapDbEntities;
	}

	public void setPractitionerMapDbEntities(Set<PractitionerMapDbEntity> practitionerMapDbEntities) {
		this.practitionerMapDbEntities = practitionerMapDbEntities;
	}

}
