package com.cantatahealth.fhir.db.model;
// Generated Oct 31, 2017 5:51:36 PM by Hibernate Tools 4.3.1.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * IdentifierDbEntity generated by hbm2java
 */
@Entity
@Table(name = "Identifier", schema = "dbo", catalog = "FHIRDB")
public class IdentifierDbEntity implements java.io.Serializable {

	private long id;
	private String useAlias;
	private String system;
	private String value;
	private Set<PatientMapDbEntity> patientMapDbEntities = new HashSet<PatientMapDbEntity>(0);

	public IdentifierDbEntity() {
	}

	public IdentifierDbEntity(long id) {
		this.id = id;
	}

	public IdentifierDbEntity(long id, String useAlias, String system, String value,
			Set<PatientMapDbEntity> patientMapDbEntities) {
		this.id = id;
		this.useAlias = useAlias;
		this.system = system;
		this.value = value;
		this.patientMapDbEntities = patientMapDbEntities;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false, precision = 18, scale = 0)
	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	@Column(name = "use_alias")
	public String getUseAlias() {
		return this.useAlias;
	}

	public void setUseAlias(String useAlias) {
		this.useAlias = useAlias;
	}

	@Column(name = "system")
	public String getSystem() {
		return this.system;
	}

	public void setSystem(String system) {
		this.system = system;
	}

	@Column(name = "value")
	public String getValue() {
		return this.value;
	}

	public void setValue(String value) {
		this.value = value;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "identifierDbEntity")
	public Set<PatientMapDbEntity> getPatientMapDbEntities() {
		return this.patientMapDbEntities;
	}

	public void setPatientMapDbEntities(Set<PatientMapDbEntity> patientMapDbEntities) {
		this.patientMapDbEntities = patientMapDbEntities;
	}

}
