package com.cantatahealth.fhir.db.model;
// Generated Oct 31, 2017 5:51:36 PM by Hibernate Tools 4.3.1.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * ImmunizationMapDbEntity generated by hbm2java
 */
@Entity
@Table(name = "ImmunizationMap", schema = "dbo", catalog = "FHIRDB")
public class ImmunizationMapDbEntity implements java.io.Serializable {

	private long id;
	private ImmunizationDbEntity immunizationDbEntity;
	private LocationDbEntity locationDbEntity;
	private PractitionerDbEntity practitionerDbEntity;

	public ImmunizationMapDbEntity() {
	}

	public ImmunizationMapDbEntity(long id, ImmunizationDbEntity immunizationDbEntity) {
		this.id = id;
		this.immunizationDbEntity = immunizationDbEntity;
	}

	public ImmunizationMapDbEntity(long id, ImmunizationDbEntity immunizationDbEntity,
			LocationDbEntity locationDbEntity, PractitionerDbEntity practitionerDbEntity) {
		this.id = id;
		this.immunizationDbEntity = immunizationDbEntity;
		this.locationDbEntity = locationDbEntity;
		this.practitionerDbEntity = practitionerDbEntity;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false, precision = 18, scale = 0)
	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "immunization", nullable = false)
	public ImmunizationDbEntity getImmunizationDbEntity() {
		return this.immunizationDbEntity;
	}

	public void setImmunizationDbEntity(ImmunizationDbEntity immunizationDbEntity) {
		this.immunizationDbEntity = immunizationDbEntity;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "location")
	public LocationDbEntity getLocationDbEntity() {
		return this.locationDbEntity;
	}

	public void setLocationDbEntity(LocationDbEntity locationDbEntity) {
		this.locationDbEntity = locationDbEntity;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "practitioner")
	public PractitionerDbEntity getPractitionerDbEntity() {
		return this.practitionerDbEntity;
	}

	public void setPractitionerDbEntity(PractitionerDbEntity practitionerDbEntity) {
		this.practitionerDbEntity = practitionerDbEntity;
	}

}
