package com.cantatahealth.fhir.db.model;
// Generated Oct 31, 2017 5:51:36 PM by Hibernate Tools 4.3.1.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * MedicationAdministrationMapDbEntity generated by hbm2java
 */
@Entity
@Table(name = "MedicationAdministrationMap", schema = "dbo", catalog = "FHIRDB")
public class MedicationAdministrationMapDbEntity implements java.io.Serializable {

	private long id;
	private MedicationAdministrationDbEntity medicationAdministrationDbEntity;
	private PractitionerDbEntity practitionerDbEntity;

	public MedicationAdministrationMapDbEntity() {
	}

	public MedicationAdministrationMapDbEntity(long id,
			MedicationAdministrationDbEntity medicationAdministrationDbEntity) {
		this.id = id;
		this.medicationAdministrationDbEntity = medicationAdministrationDbEntity;
	}

	public MedicationAdministrationMapDbEntity(long id,
			MedicationAdministrationDbEntity medicationAdministrationDbEntity,
			PractitionerDbEntity practitionerDbEntity) {
		this.id = id;
		this.medicationAdministrationDbEntity = medicationAdministrationDbEntity;
		this.practitionerDbEntity = practitionerDbEntity;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false, precision = 18, scale = 0)
	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "medicationadministration", nullable = false)
	public MedicationAdministrationDbEntity getMedicationAdministrationDbEntity() {
		return this.medicationAdministrationDbEntity;
	}

	public void setMedicationAdministrationDbEntity(MedicationAdministrationDbEntity medicationAdministrationDbEntity) {
		this.medicationAdministrationDbEntity = medicationAdministrationDbEntity;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "practitioner")
	public PractitionerDbEntity getPractitionerDbEntity() {
		return this.practitionerDbEntity;
	}

	public void setPractitionerDbEntity(PractitionerDbEntity practitionerDbEntity) {
		this.practitionerDbEntity = practitionerDbEntity;
	}

}
