package com.cantatahealth.fhir.db.model;
// Generated Oct 31, 2017 5:51:36 PM by Hibernate Tools 4.3.1.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * ObservationMapDbEntity generated by hbm2java
 */
@Entity
@Table(name = "ObservationMap", schema = "dbo", catalog = "FHIRDB")
public class ObservationMapDbEntity implements java.io.Serializable {

	private long id;
	private ObservationDbEntity observationDbEntity;
	private PractitionerDbEntity practitionerDbEntity;
	private RangeDbEntity rangeDbEntity;

	public ObservationMapDbEntity() {
	}

	public ObservationMapDbEntity(long id, ObservationDbEntity observationDbEntity) {
		this.id = id;
		this.observationDbEntity = observationDbEntity;
	}

	public ObservationMapDbEntity(long id, ObservationDbEntity observationDbEntity,
			PractitionerDbEntity practitionerDbEntity, RangeDbEntity rangeDbEntity) {
		this.id = id;
		this.observationDbEntity = observationDbEntity;
		this.practitionerDbEntity = practitionerDbEntity;
		this.rangeDbEntity = rangeDbEntity;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false, precision = 18, scale = 0)
	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "observation", nullable = false)
	public ObservationDbEntity getObservationDbEntity() {
		return this.observationDbEntity;
	}

	public void setObservationDbEntity(ObservationDbEntity observationDbEntity) {
		this.observationDbEntity = observationDbEntity;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "practitioner")
	public PractitionerDbEntity getPractitionerDbEntity() {
		return this.practitionerDbEntity;
	}

	public void setPractitionerDbEntity(PractitionerDbEntity practitionerDbEntity) {
		this.practitionerDbEntity = practitionerDbEntity;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "referencerange")
	public RangeDbEntity getRangeDbEntity() {
		return this.rangeDbEntity;
	}

	public void setRangeDbEntity(RangeDbEntity rangeDbEntity) {
		this.rangeDbEntity = rangeDbEntity;
	}

}
