package com.cantatahealth.fhir.db.model;
// Generated Oct 31, 2017 5:51:36 PM by Hibernate Tools 4.3.1.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * ProcedureMapDbEntity generated by hbm2java
 */
@Entity
@Table(name = "ProcedureMap", schema = "dbo", catalog = "FHIRDB")
public class ProcedureMapDbEntity implements java.io.Serializable {

	private long id;
	private ConditionDbEntity conditionDbEntity;
	private ObservationDbEntity observationDbEntity;
	private PractitionerDbEntity practitionerDbEntity;
	private ProcedureDbEntity procedureDbEntity;

	public ProcedureMapDbEntity() {
	}

	public ProcedureMapDbEntity(long id, ProcedureDbEntity procedureDbEntity) {
		this.id = id;
		this.procedureDbEntity = procedureDbEntity;
	}

	public ProcedureMapDbEntity(long id, ConditionDbEntity conditionDbEntity, ObservationDbEntity observationDbEntity,
			PractitionerDbEntity practitionerDbEntity, ProcedureDbEntity procedureDbEntity) {
		this.id = id;
		this.conditionDbEntity = conditionDbEntity;
		this.observationDbEntity = observationDbEntity;
		this.practitionerDbEntity = practitionerDbEntity;
		this.procedureDbEntity = procedureDbEntity;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false, precision = 18, scale = 0)
	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "condition")
	public ConditionDbEntity getConditionDbEntity() {
		return this.conditionDbEntity;
	}

	public void setConditionDbEntity(ConditionDbEntity conditionDbEntity) {
		this.conditionDbEntity = conditionDbEntity;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "observation")
	public ObservationDbEntity getObservationDbEntity() {
		return this.observationDbEntity;
	}

	public void setObservationDbEntity(ObservationDbEntity observationDbEntity) {
		this.observationDbEntity = observationDbEntity;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "practitioner")
	public PractitionerDbEntity getPractitionerDbEntity() {
		return this.practitionerDbEntity;
	}

	public void setPractitionerDbEntity(PractitionerDbEntity practitionerDbEntity) {
		this.practitionerDbEntity = practitionerDbEntity;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "procedure_alias", nullable = false)
	public ProcedureDbEntity getProcedureDbEntity() {
		return this.procedureDbEntity;
	}

	public void setProcedureDbEntity(ProcedureDbEntity procedureDbEntity) {
		this.procedureDbEntity = procedureDbEntity;
	}

}
