package com.cantatahealth.fhir.db.model;
// Generated Oct 31, 2017 5:51:36 PM by Hibernate Tools 4.3.1.Final

import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * QuantityDbEntity generated by hbm2java
 */
@Entity
@Table(name = "Quantity", schema = "dbo", catalog = "FHIRDB")
public class QuantityDbEntity implements java.io.Serializable {

	private long id;
	private CodingDbEntity codingDbEntity;
	private BigDecimal value;
	private String unit;
	private String system;
	private Set<RangeDbEntity> rangeDbEntitiesForLow = new HashSet<RangeDbEntity>(0);
	private Set<DosageDbEntity> dosageDbEntities = new HashSet<DosageDbEntity>(0);
	private Set<RangeDbEntity> rangeDbEntitiesForHigh = new HashSet<RangeDbEntity>(0);
	private Set<ObservationDbEntity> observationDbEntities = new HashSet<ObservationDbEntity>(0);

	public QuantityDbEntity() {
	}

	public QuantityDbEntity(long id) {
		this.id = id;
	}

	public QuantityDbEntity(long id, CodingDbEntity codingDbEntity, BigDecimal value, String unit, String system,
			Set<RangeDbEntity> rangeDbEntitiesForLow, Set<DosageDbEntity> dosageDbEntities,
			Set<RangeDbEntity> rangeDbEntitiesForHigh, Set<ObservationDbEntity> observationDbEntities) {
		this.id = id;
		this.codingDbEntity = codingDbEntity;
		this.value = value;
		this.unit = unit;
		this.system = system;
		this.rangeDbEntitiesForLow = rangeDbEntitiesForLow;
		this.dosageDbEntities = dosageDbEntities;
		this.rangeDbEntitiesForHigh = rangeDbEntitiesForHigh;
		this.observationDbEntities = observationDbEntities;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false, precision = 18, scale = 0)
	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "comparator")
	public CodingDbEntity getCodingDbEntity() {
		return this.codingDbEntity;
	}

	public void setCodingDbEntity(CodingDbEntity codingDbEntity) {
		this.codingDbEntity = codingDbEntity;
	}

	@Column(name = "value", precision = 18)
	public BigDecimal getValue() {
		return this.value;
	}

	public void setValue(BigDecimal value) {
		this.value = value;
	}

	@Column(name = "unit")
	public String getUnit() {
		return this.unit;
	}

	public void setUnit(String unit) {
		this.unit = unit;
	}

	@Column(name = "system")
	public String getSystem() {
		return this.system;
	}

	public void setSystem(String system) {
		this.system = system;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "quantityDbEntityByLow")
	public Set<RangeDbEntity> getRangeDbEntitiesForLow() {
		return this.rangeDbEntitiesForLow;
	}

	public void setRangeDbEntitiesForLow(Set<RangeDbEntity> rangeDbEntitiesForLow) {
		this.rangeDbEntitiesForLow = rangeDbEntitiesForLow;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "quantityDbEntity")
	public Set<DosageDbEntity> getDosageDbEntities() {
		return this.dosageDbEntities;
	}

	public void setDosageDbEntities(Set<DosageDbEntity> dosageDbEntities) {
		this.dosageDbEntities = dosageDbEntities;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "quantityDbEntityByHigh")
	public Set<RangeDbEntity> getRangeDbEntitiesForHigh() {
		return this.rangeDbEntitiesForHigh;
	}

	public void setRangeDbEntitiesForHigh(Set<RangeDbEntity> rangeDbEntitiesForHigh) {
		this.rangeDbEntitiesForHigh = rangeDbEntitiesForHigh;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "quantityDbEntity")
	public Set<ObservationDbEntity> getObservationDbEntities() {
		return this.observationDbEntities;
	}

	public void setObservationDbEntities(Set<ObservationDbEntity> observationDbEntities) {
		this.observationDbEntities = observationDbEntities;
	}

}
