package com.cantatahealth.fhir.db.model;
// Generated Oct 31, 2017 5:51:36 PM by Hibernate Tools 4.3.1.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * RangeDbEntity generated by hbm2java
 */
@Entity
@Table(name = "Range", schema = "dbo", catalog = "FHIRDB")
public class RangeDbEntity implements java.io.Serializable {

	private long id;
	private QuantityDbEntity quantityDbEntityByLow;
	private QuantityDbEntity quantityDbEntityByHigh;
	private Set<ObservationMapDbEntity> observationMapDbEntities = new HashSet<ObservationMapDbEntity>(0);

	public RangeDbEntity() {
	}

	public RangeDbEntity(long id) {
		this.id = id;
	}

	public RangeDbEntity(long id, QuantityDbEntity quantityDbEntityByLow, QuantityDbEntity quantityDbEntityByHigh,
			Set<ObservationMapDbEntity> observationMapDbEntities) {
		this.id = id;
		this.quantityDbEntityByLow = quantityDbEntityByLow;
		this.quantityDbEntityByHigh = quantityDbEntityByHigh;
		this.observationMapDbEntities = observationMapDbEntities;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false, precision = 18, scale = 0)
	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "low")
	public QuantityDbEntity getQuantityDbEntityByLow() {
		return this.quantityDbEntityByLow;
	}

	public void setQuantityDbEntityByLow(QuantityDbEntity quantityDbEntityByLow) {
		this.quantityDbEntityByLow = quantityDbEntityByLow;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "high")
	public QuantityDbEntity getQuantityDbEntityByHigh() {
		return this.quantityDbEntityByHigh;
	}

	public void setQuantityDbEntityByHigh(QuantityDbEntity quantityDbEntityByHigh) {
		this.quantityDbEntityByHigh = quantityDbEntityByHigh;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "rangeDbEntity")
	public Set<ObservationMapDbEntity> getObservationMapDbEntities() {
		return this.observationMapDbEntities;
	}

	public void setObservationMapDbEntities(Set<ObservationMapDbEntity> observationMapDbEntities) {
		this.observationMapDbEntities = observationMapDbEntities;
	}

}
