package com.cantatahealth.fhir.db.model;
// Generated Oct 31, 2017 5:51:36 PM by Hibernate Tools 4.3.1.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * ReactionnDbEntity generated by hbm2java
 */
@Entity
@Table(name = "Reaction", schema = "dbo", catalog = "FHIRDB")
public class ReactionnDbEntity implements java.io.Serializable {

	private long id;
	private CodingDbEntity codingDbEntityByManifestation;
	private CodingDbEntity codingDbEntityBySeverity;
	private Date onset;
	private String note;
	private Set<AllergyIntoleranceMapDbEntity> allergyIntoleranceMapDbEntities = new HashSet<AllergyIntoleranceMapDbEntity>(
			0);

	public ReactionnDbEntity() {
	}

	public ReactionnDbEntity(long id) {
		this.id = id;
	}

	public ReactionnDbEntity(long id, CodingDbEntity codingDbEntityByManifestation,
			CodingDbEntity codingDbEntityBySeverity, Date onset, String note,
			Set<AllergyIntoleranceMapDbEntity> allergyIntoleranceMapDbEntities) {
		this.id = id;
		this.codingDbEntityByManifestation = codingDbEntityByManifestation;
		this.codingDbEntityBySeverity = codingDbEntityBySeverity;
		this.onset = onset;
		this.note = note;
		this.allergyIntoleranceMapDbEntities = allergyIntoleranceMapDbEntities;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false, precision = 18, scale = 0)
	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "manifestation")
	public CodingDbEntity getCodingDbEntityByManifestation() {
		return this.codingDbEntityByManifestation;
	}

	public void setCodingDbEntityByManifestation(CodingDbEntity codingDbEntityByManifestation) {
		this.codingDbEntityByManifestation = codingDbEntityByManifestation;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "severity")
	public CodingDbEntity getCodingDbEntityBySeverity() {
		return this.codingDbEntityBySeverity;
	}

	public void setCodingDbEntityBySeverity(CodingDbEntity codingDbEntityBySeverity) {
		this.codingDbEntityBySeverity = codingDbEntityBySeverity;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "onset", length = 23)
	public Date getOnset() {
		return this.onset;
	}

	public void setOnset(Date onset) {
		this.onset = onset;
	}

	@Column(name = "note")
	public String getNote() {
		return this.note;
	}

	public void setNote(String note) {
		this.note = note;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "reactionnDbEntity")
	public Set<AllergyIntoleranceMapDbEntity> getAllergyIntoleranceMapDbEntities() {
		return this.allergyIntoleranceMapDbEntities;
	}

	public void setAllergyIntoleranceMapDbEntities(Set<AllergyIntoleranceMapDbEntity> allergyIntoleranceMapDbEntities) {
		this.allergyIntoleranceMapDbEntities = allergyIntoleranceMapDbEntities;
	}

}
