package com.cantatahealth.fhir.db.model;
// Generated Oct 31, 2017 5:51:36 PM by Hibernate Tools 4.3.1.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * ResourceDbEntity generated by hbm2java
 */
@Entity
@Table(name = "Resource", schema = "dbo", catalog = "FHIRDB")
public class ResourceDbEntity implements java.io.Serializable {

	private long resourcekey;
	private String resourcename;
	private String resourcecode;
	private String resourcetype;
	private String content;
	private Boolean supported;
	private Boolean cmdRead;
	private Boolean cmdUpdate;
	private Boolean cmddelete;
	private Boolean cmdcreate;
	private Boolean cmdsearch;

	public ResourceDbEntity() {
	}

	public ResourceDbEntity(long resourcekey, String resourcename) {
		this.resourcekey = resourcekey;
		this.resourcename = resourcename;
	}

	public ResourceDbEntity(long resourcekey, String resourcename, String resourcecode, String resourcetype,
			String content, Boolean supported, Boolean cmdRead, Boolean cmdUpdate, Boolean cmddelete, Boolean cmdcreate,
			Boolean cmdsearch) {
		this.resourcekey = resourcekey;
		this.resourcename = resourcename;
		this.resourcecode = resourcecode;
		this.resourcetype = resourcetype;
		this.content = content;
		this.supported = supported;
		this.cmdRead = cmdRead;
		this.cmdUpdate = cmdUpdate;
		this.cmddelete = cmddelete;
		this.cmdcreate = cmdcreate;
		this.cmdsearch = cmdsearch;
	}

	@Id

	@Column(name = "resourcekey", unique = true, nullable = false, precision = 18, scale = 0)
	public long getResourcekey() {
		return this.resourcekey;
	}

	public void setResourcekey(long resourcekey) {
		this.resourcekey = resourcekey;
	}

	@Column(name = "resourcename", nullable = false)
	public String getResourcename() {
		return this.resourcename;
	}

	public void setResourcename(String resourcename) {
		this.resourcename = resourcename;
	}

	@Column(name = "resourcecode")
	public String getResourcecode() {
		return this.resourcecode;
	}

	public void setResourcecode(String resourcecode) {
		this.resourcecode = resourcecode;
	}

	@Column(name = "resourcetype", length = 50)
	public String getResourcetype() {
		return this.resourcetype;
	}

	public void setResourcetype(String resourcetype) {
		this.resourcetype = resourcetype;
	}

	@Column(name = "content")
	public String getContent() {
		return this.content;
	}

	public void setContent(String content) {
		this.content = content;
	}

	@Column(name = "supported")
	public Boolean getSupported() {
		return this.supported;
	}

	public void setSupported(Boolean supported) {
		this.supported = supported;
	}

	@Column(name = "cmdRead")
	public Boolean getCmdRead() {
		return this.cmdRead;
	}

	public void setCmdRead(Boolean cmdRead) {
		this.cmdRead = cmdRead;
	}

	@Column(name = "cmdUpdate")
	public Boolean getCmdUpdate() {
		return this.cmdUpdate;
	}

	public void setCmdUpdate(Boolean cmdUpdate) {
		this.cmdUpdate = cmdUpdate;
	}

	@Column(name = "cmddelete")
	public Boolean getCmddelete() {
		return this.cmddelete;
	}

	public void setCmddelete(Boolean cmddelete) {
		this.cmddelete = cmddelete;
	}

	@Column(name = "cmdcreate")
	public Boolean getCmdcreate() {
		return this.cmdcreate;
	}

	public void setCmdcreate(Boolean cmdcreate) {
		this.cmdcreate = cmdcreate;
	}

	@Column(name = "cmdsearch")
	public Boolean getCmdsearch() {
		return this.cmdsearch;
	}

	public void setCmdsearch(Boolean cmdsearch) {
		this.cmdsearch = cmdsearch;
	}

}
